---
- name: Uninstall docker engine
  hosts: 
  - Docker-Master
  - Docker-Slave
  tasks:
  - name: Uninstall Docker Engine
    shell: apt purge  docker-ce docker-ce-cli containerd.io -y ; rm -rf /var/lib/docker ; rm -rf /var/lib/containerd
  - name: Remove GPG Keys
    shell: rm /usr/share/keyrings/docker-archive-keyring.gpg
  - name: Remove APT Repository
    shell: rm /etc/apt/sources.list.d/docker.list
  - name: Clean APT
    shell: apt autoremove -y
  - name: reload systemd
    systemd:
      daemon-reload: yes
