---
- name: Initiate Docker Swarm
  hosts: 
  - Docker-Master
  tasks:
  - name: Initiate Docker Swarm
    shell: docker swarm init
  - name: Save Join Command
    shell: docker swarm join-token worker
    register: join_command_test
  - name: Debug join cluster command
    debug:
      msg: "{{ join_command_test.stdout_lines[2] }}"  
  - name: Copy join command to local file
    local_action: copy content="{{ join_command_test.stdout_lines[2] }}" dest="/tmp/join_command.sh" mode=0755

- name: Join the Docker Swarm
  hosts: 
  - Docker-Slave
  tasks:
  - name: Copy the Docker Swarm join command
    copy:
      src: /tmp/join_command.sh 
      dest: /tmp
      mode: 0755
  - name: Join the Docker Swarm
    shell: /tmp/join_command.sh
  - name: Remove Join Command
    shell: rm /tmp/join_command.sh

- name: Remove local file
  hosts: localhost
  tasks:
  - name: Remove local join file
    shell: rm /tmp/join_command.sh