---
- name: Install docker engine
  hosts: 
  - Docker-Master
  - Docker-Slave
  tasks:
  - name: Update repositories cache and install docker needed packages
    apt:
      update_cache: yes
      state: latest
      pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  - name: Get OS Distribution
    shell: cat /etc/os-release | grep -w ID |cut -d "=" -f 2 > $HOME/OS_distrib.txt
  - name: Add Docker GPG key
    shell: curl -fsSL https://download.docker.com/linux/$(cat $HOME/OS_distrib.txt)/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - name: Remove OS_distrib file
    shell: rm $HOME/OS_distrib.txt 
  - name: Add Docker APT Repository
    shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - name: Install Docker Packages
    apt:
      update_cache: yes
      state: latest
      pkg:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
  - name: Enable Docker to run as non-root user
    shell: groupadd docker ; service docker restart ; usermod -a -G docker mit